# Generated by Django 3.1.7 on 2021-05-22 09:15

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='users/avatar.png', upload_to=accounts.models.user_directory_path)),
                ('bio', models.TextField(blank=True, max_length=5500)),
                ('fullName', models.CharField(blank=True, default='wvWm6', max_length=221)),
                ('dr', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='zJRaBEmE', max_length=250, unique=True)),
                ('facebook', models.URLField(blank=True, max_length=222)),
                ('twitter', models.URLField(blank=True, max_length=222)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
