# Generated by Django 3.1.7 on 2021-06-09 10:26

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0011_auto_20210607_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, default='AgYmP', max_length=221),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='VT5qCp4y', max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='siteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHome', models.CharField(blank=True, max_length=111)),
                ('imageHome', models.ImageField(upload_to=accounts.models.user_directory_path)),
                ('bioHome', models.TextField(blank=True, max_length=5500)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
