# Generated by Django 3.1.7 on 2021-06-09 10:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210609_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='bioForum',
            field=models.TextField(blank=True, max_length=5500),
        ),
        migrations.AddField(
            model_name='sitename',
            name='bioVideo',
            field=models.TextField(blank=True, max_length=5500),
        ),
        migrations.AddField(
            model_name='sitename',
            name='imageForum',
            field=models.ImageField(default=1, upload_to=accounts.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitename',
            name='imageVideo',
            field=models.ImageField(default=1, upload_to=accounts.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitename',
            name='nameForum',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AddField(
            model_name='sitename',
            name='nameVideo',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, default='hcnEY', max_length=221),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='SuJmTckC', max_length=250, unique=True),
        ),
    ]
